childPipelines:
  scmUrls:
    - git@gitlab.com:tkyi/testing.git#test
    - git@gitlab.com:tkyi/testing.git#test:test
    - git@gitlab.com:tkyi/testing.git
    #- git@gitlab.com:tkyi/subscribe.git
jobs:
  main:
    image: node:8
    steps:
        - secrets: echo A:$A_SECRET && echo B:$B_SECRET && echo C:$C_SECRET
        - art: cat $SD_SOURCE_DIR/ascii-art.txt
    requires: [~pr, ~commit]
    secrets:
      - A_SECRET
      - B_SECRET
      - C_SECRET
